# Generated by Django 4.2.5 on 2023-09-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_toy_alter_feeding_options_alter_feeding_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeding',
            options={},
        ),
        migrations.AddField(
            model_name='fish',
            name='toys',
            field=models.ManyToManyField(to='main_app.toy'),
        ),
    ]
